version: '3.8'

services:
  eureka-server:
    image: eureka-server
    container_name: eureka-server
    build:
      context: ../Microservice-Apache-Kafka/eureka-server/
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
    networks:
      - eureka-network

  gateway:
    image: gateway
    container_name: gateway
    build:
      context: ../Microservice-Apache-Kafka/gateway/
      dockerfile: Dockerfile
    ports:
      - "8085:8085"
    networks:
      - eureka-network

networks:
  eureka-network:
    driver: bridge