server:
  port: 8085

eureka:
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka

spring:
  application:
    name: gateway
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders:
              - "*"
            allowCredentials: true
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: orders-service
          uri: lb://orders-service
          predicates:
            - Path=/api/v1/orders/**

        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/api/v1/payment/**

        - id: shipping-service
          uri: lb://shipping-service
          predicates:
            - Path=/api/v1/shipping/**

        - id: notifications-service
          uri: lb://notifications-service
          predicates:
            - Path=/api/v1/notifications/**