server:
  port: 8193

eureka:
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: shipping-service
#  jpa:
#    generate-ddl: true
#    defer-datasource-initialization: false
#    hibernate:
#      ddl-auto: none
#    show-sql: false
#    properties:
#      hibernate:
#        format_sql: true
#    open-in-view: false
#  flyway:
#    enabled: true
#    locations: classpath:db/migration
#    baseline-on-migrate: true
  kafka:
    bootstrap-servers: localhost:9092
    retries: 10
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      group-id: shipping-event-group
      properties.spring.json.trusted.packages: "*"

logging:
  file:
    name: logfile.log
#    max-size: 5MB
#    max-history: 1